version: '3.8'
services:
  postgres:
    container_name: pg_db
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres 
    ports:
      - '5050:80' 
    environment:
      - PGADMIN_DEFAULT_EMAIl=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
